# Monitoring commun
management.endpoints.web.exposure.include=*

# Logging par defaut
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

# ========== INTERNAL SERVICE TOKEN ==========
internal.service.token=${INTERNAL_SERVICE_TOKEN:internal-service-token-2026}

# ========== REDIS CONFIGURATION ==========
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=${REDIS_TIMEOUT:2000ms}

# Timezone par defaut
spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Connexion a Consul (surchargeable par service si besoin)
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-interval=10s

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Desactiver completement lexecution automatique des scripts SQL de data.sql
spring.sql.init.mode=never

#Variable Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}