spring.application.name=document-service
server.port=${SERVER_PORT:8082}

# Consul
spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=${CONSUL_PORT:8500}

# R2DBC
spring.r2dbc.url=${SPRING_R2DBC_URL}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD}
spring.r2dbc.pool.initial-size=${SPRING_R2DBC_POOL_INITIAL_SIZE:5}
spring.r2dbc.pool.max-size=${SPRING_R2DBC_POOL_MAX_SIZE:20}

# Flyway
spring.flyway.enabled=true
spring.flyway.url=${SPRING_FLYWAY_URL}
spring.flyway.user=${SPRING_FLYWAY_USER}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD}
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=true
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=false

# Storage S3 en prod
storage.type=${STORAGE_TYPE:s3}
storage.upload-dir=
storage.s3.bucket=${S3_BUCKET}
storage.s3.region=${S3_REGION:eu-west-1}
storage.s3.access-key=${S3_ACCESS_KEY}
storage.s3.secret-key=${S3_SECRET_KEY}

# Logging prod (moins verbeux)
logging.level.org.flywaydb=WARN
logging.level.io.r2dbc.postgresql=WARN
logging.level.com.architecte=INFO