spring.application.name=gateway-service
server.port=9999

# Consul (dynamique)
spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=${CONSUL_PORT:8500}

# ========== JWT CONFIGURATION ==========
jwt.secret=${JWT_SECRET:temporarySecretForDev}
jwt.expiration=${JWT_EXPIRATION:600000000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:30000000000}

# Activer discovery pour router automatiquement
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#timeout plus long pour le clonage
spring.cloud.gateway.httpclient.response-timeout=60s
spring.cloud.gateway.httpclient.connect-timeout=10000

# Retry seulement sur GET
spring.cloud.gateway.default-filters[0]=Retry=1,methods=GET,series=SERVER_ERROR

#Log
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.reactor.netty=DEBUG